[project]
name = "aws-python-lambda-template"
version = "0.1.0"
description = "Template for AWS Lambda using the traditional Serverless Framework"
authors = [
    {name = "Walter Cardozo", email = "waltercrdz@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3==1.42.86",
    "httpx==0.28.1",
    "mysql-connector-python==9.6.0",
]

[dependency-groups]
dev = [
    "mypy==1.20.0",
    "pytest==9.0.3",
    "coverage==7.13.5",
    "ruff==0.15.10",
]

[tool.pytest.ini_options]
pythonpath = "src"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
files = "src"
strict = true
python_version = "3.14"
disallow_untyped_defs = true
ignore_missing_imports = false
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_optional = false
