version: "3"

services:
  db:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: products
      MYSQL_USER: products
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - ./etc/database:/docker-entrypoint-initdb.d

  products-api:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    env_file:
      - etc/.env
    volumes:
      - ~/.aws/:/root/.aws:ro
    restart: "no"
    depends_on:
      - db