[project]
name = "python-microservice-template"
version = "0.1.0"
description = ""
authors = [
    {name = "Walter Cardozo", email = "waltercrdz@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi==0.129.1",
    "uvicorn==0.44.0",
    "pydantic==2.12.5",
    "mysql-connector-python==9.6.0",
]

[dependency-groups]
dev = [
    "pytest==9.0.3",
    "coverage==7.13.5",
    "mypy==1.20.0",
    "ruff==0.15.10",
    "alembic==1.18.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
target-version = "py314"
fix = true

lint.select = [
    "E",  # Pycodestyle error codes (like PEP 8 violations)
    "F",  # Pyflakes error codes (e.g., undefined variables, unused imports)
    "B",  # Bugbear (for catching potential bugs and code quality issues)
    "Q",  # flake8-Quotes (single- vs. double-quoted strings consistency)
    "A",  # flake8-annotations (type annotation enforcement)
]

exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    "venv",
    ".venv",
]

line-length = 88
lint.ignore = [
    "E203",  # Whitespace before ':', conflicts with Black's formatting
    #"E501",  # Line length (usually handled by a formatter like Black)
    "B008",  # Ignore B008 error
]

lint.fixable = [
    "Q",    # Auto-fix quotes
    "F401", # Remove unused imports
    "E",    # Formatting and style errors
]

[tool.mypy]
files = "app"
strict = true
python_version = "3.14"
disallow_untyped_defs = true
ignore_missing_imports = false
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_optional = false
